import type { Metadata } from "next";
import AuthProvider from "@/AuthProvider";
import NavMenu from "./NavMenu";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className='container'>
            <NavMenu />
            {children}
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
